config/routes.rb
# Support Helpdesk - Redmine plugin
# Copyright (C) 2012 Paul Van de Vreede
#
# This file is part of Support Helpdesk.
#
# Support Helpdesk is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Support Helpdesk is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Support Helpdesk.  If not, see <http://www.gnu.org/licenses/>.

resources :support_helpdesk_settings, :controller => 'support_helpdesk_setting', :path => '/support/settings' do
  post 'activate', :on => :member
end

# routes to RuoteKit
match '/_ruote' => RuoteKit::Application
match '/_ruote/*path' => RuoteKit::Application

app/models/support_helpdesk_setting.rb
# Support Helpdesk - Redmine plugin
# Copyright (C) 2012 Paul Van de Vreede
#
# This file is part of Support Helpdesk.
#
# Support Helpdesk is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Support Helpdesk is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Support Helpdesk.  If not, see <http://www.gnu.org/licenses/>.

# terrible hack to make sure that the plugin settings are loaded when this class
# is loaded so that it can use the settings for the view path class var.
require_relative "../mailers/support_helpdesk_mailer"

class SupportHelpdeskSetting < ActiveRecord::Base
  unloadable

  belongs_to :project
  belongs_to :tracker
  belongs_to :issue_status
  belongs_to :email_domain_custom_field, :class_name => 'ProjectCustomField', :foreign_key => 'email_domain_custom_field_id'
  belongs_to :priority, :class_name => 'IssuePriority', :foreign_key => 'priority_id'
  belongs_to :author, :class_name => 'User', :foreign_key => 'author_id'
  belongs_to :assignee_group, :class_name => 'Group', :foreign_key => 'assignee_group_id'
  belongs_to :new_status, :class_name => 'IssueStatus', :foreign_key => 'new_status_id'
  belongs_to :last_assigned_user, :class_name => 'User', :foreign_key => 'last_assigned_user_id'
  belongs_to :reply_email_custom_field, :class_name => 'IssueCustomField', :foreign_key => 'reply_email_custom_field_id'
  belongs_to :type_custom_field, :class_name => 'IssueCustomField', :foreign_key => 'type_custom_field_id'
  has_many :issues_support_settings, :dependent => :destroy
  has_many :issues, :through => :issues_support_settings

  validates :new_status_id, :presence => true
  validates :project_id, :presence => true
  validates :author_id, :presence => true
  validates :to_email_address, :presence => true
  validates :from_email_address, :presence => true
  validates :tracker_id, :presence => true
  validates :reply_email_custom_field_id, :presence => true
  validates :type_custom_field_id, :presence => true
  validates :created_template_name, :presence => true
  validates :closed_template_name, :presence => true
  validates :question_template_name, :presence => true
  validates :name, :presence => true
  validates :assignee_group_id, :presence => true
  validates :priority_id, :presence => true

  validates_associated :project
  validates_associated :tracker
  validates_associated :issue_status
  validates_associated :priority

  scope :active, where(:active => true)

  def is_ignored_email_domain(email)
    # if there are no domains to ignore return
    return false if self.domains_to_ignore.nil?

    #other split the domains and check
    domain_array = self.domains_to_ignore.downcase.split(";")
    if domain_array.include?(email.from[0].split('@')[1].downcase)
      return true
    end

    false
  end

  def get_email_reply_string(email)
    return email.from[0] if not self.reply_all_for_outgoing

    #build semicolon string from all fields if not the support email
    email_array = email.to.to_a + email.from.to_a + email.cc.to_a

    email_array.find_all { |e| e.downcase unless e.downcase == self.to_email_address.downcase }.join("; ")
  end
end

app/controllers/support_helpdesk_setting_controller.rb
# Support Helpdesk - Redmine plugin
# Copyright (C) 2012 Paul Van de Vreede
#
# This file is part of Support Helpdesk.
#
# Support Helpdesk is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Support Helpdesk is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Support Helpdesk.  If not, see <http://www.gnu.org/licenses/>.

class SupportHelpdeskSettingController < ApplicationController
  include SupportHelpdeskSettingHelper

  unloadable
  layout 'admin'

  before_filter :require_admin
  before_filter :get_setting,      :only => [:edit, :update, :activate, :destroy]
  before_filter :get_for_new_edit, :only => [:new, :edit]

  def index
  	@settings = SupportHelpdeskSetting.includes(:project, :tracker)

  	respond_to do |format|
  		format.html
  	end
  end

  def new
  	@setting = SupportHelpdeskSetting.new

  	respond_to do |format|
  		format.html
  	end
  end

  def create
    @setting = SupportHelpdeskSetting.new(params[:support_helpdesk_setting])

    respond_to do |format|
      if @setting.save
        format.html { redirect_to(support_helpdesk_settings_url, :notice => "Support setting successfully created.") }
      else
        get_for_new_edit
        format.html { render :action => "new" }
      end
    end
  end

  def edit
    respond_to do |format|
      format.html
    end
  end

  def update
    respond_to do |format|
      if @setting.update_attributes(params[:support_helpdesk_setting])
        format.html { redirect_to(support_helpdesk_settings_url, :notice => "Support setting successfully updated.") }
      else
        get_for_new_edit
        format.html { render :action => "edit" }
      end
    end
  end

  def activate
    @setting.active = !@setting.active
    logger.debug(@setting.inspect)

    if @setting.save
      redirect_to(support_helpdesk_settings_url, :notice => "Setting updated successfully.")
    else
      redirect_to(support_helpdesk_settings_url, :error => "Could not update setting.")
    end
  end

  def destroy
    @setting.destroy

    respond_to do |format|
      format.html {redirect_to(support_helpdesk_settings_url, :notice => "Setting deleted.")}
    end
  end

  private
  def get_setting
    @setting = SupportHelpdeskSetting.find(params[:id])
  end

  def get_for_new_edit
    @projects = Project.order("name")
    @trackers = Tracker.all
    @issue_custom_fields = CustomField.where(:type => "IssueCustomField")
    @project_custom_fields = CustomField.where(:type => "ProjectCustomField")
    @groups = Group.all
    @users = User.where("type != ?", "AnonymousUser")
    @groups_users = @users + @groups
    @statuses = IssueStatus.all
    @priorities = IssuePriority.all

    # get list of templates to select for emails
    @template_files = Dir[File.join(Setting.plugin_support_helpdesk['support_template_path'], "*.text.erb")].reject do |f|
      f == '.' || f == '..' || f.split("/").last[0] == "_"
    end.map do |f|
      name = f.split("/").last.split(".").first
      [name, name]
    end
  end
end

app/helpers/support_helpdesk_setting_helper.rb
# Support Helpdesk - Redmine plugin
# Copyright (C) 2012 Paul Van de Vreede
#
# This file is part of Support Helpdesk.
#
# Support Helpdesk is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Support Helpdesk is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Support Helpdesk.  If not, see <http://www.gnu.org/licenses/>.

module SupportHelpdeskSettingHelper

  def search_in_checkbox_marked?(setting, text)
    if setting.search_in.nil?
      return true
    end

    setting.search_in.includes?(text)
  end

end

app/views/support_helpdesk_setting/_form.html.erb
<%= labelled_form_for(@setting) do |f| %>
<% if @setting.errors.any? %>
  <div id="errorExplanation">
    <ul>
    <% @setting.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div id="support_setting_form">
  <div class="splitcontentleft">
    <fieldset class="box tabular">
      <legend>Information</legend>
        <p>
          <%= f.text_field :name, :required => true %>
        </p>
        <p>
          <%= f.text_field :to_email_address, :required => true %>
        </p>

        <p>
          <%= f.text_field :from_email_address, :required => true %>
        </p>
        <p>
          <label for="new_status_id">
            Status for created issue
            <span class="required"> *</span>
          </label>
          <%= f.collection_select(:new_status_id, @statuses, :id, :name, :required => true) %>
        </p>
        <p>
          <label for="priority_id">
            Priority for created issue
            <span class="required"> *</span>
          </label>
          <%= f.collection_select(:priority_id, @priorities, :id, :name, :required => true) %>
        </p>
        <p>
          <label for="project_id">
            Default Project
            <span class="required"> *</span>
          </label>
          <%= f.collection_select(:project_id, @projects, :id, :name) %>
          <em class="info">
            If an email domain custom field is specified, this project will be used as the default project if the sender email address cannot be matched to any other project.
          </em>
        </p>
        <p>
          <label for="email_domain_custom_field_id">
            Email domain custom field
          </label>
          <%= f.collection_select(:email_domain_custom_field_id, @project_custom_fields, :id, :name, {:include_blank => true}) %>
          <em class="info">
            This is the custom project field where the domain name of the email will be matched from. This field should contain the domain name only, rather than a full email address, eg:<br />
            redmine.org
          </em>
        </p>
        <p>
          <label for="tracker_id">
            Tracker
            <span class="required"> *</span>
          </label>
          <%= f.collection_select(:tracker_id, @trackers, :id, :name) %>
        </p>
        <p>
          <label for="assignee_group_id">
            User or group to assign to
            <span class="required"> *</span>
          </label>
          <%= f.collection_select(:assignee_group_id, @groups_users, :id, :name) %>
        </p>
        <p>
          <label for="author_id">
            Issue author
            <span class="required"> *</span>
          </label>
          <%= f.collection_select(:author_id, @users, :id, :name) %>
        </p>
        <p>
          <label for="reply_email_custom_field_id">
            Reply email custom field
            <span class="required"> *</span>
          </label>
          <%= f.collection_select(:reply_email_custom_field_id, @issue_custom_fields, :id, :name) %>
          <em class="info">
            This is a custom issue field where the sender's email address will be stored for information and to send creation, closed and user question emails back to the support user.
          </em>
        </p>
        <p>
          <label for="type_custom_field_id">
            Support type custom field
            <span class="required"> *</span>
          </label>
          <%= f.collection_select(:type_custom_field_id, @issue_custom_fields, :id, :name) %>
          <em class="info">
            This is a custom issue field the support setting name is populated so you know which support setting created it, and which type of support the issue belongs to.
          </em>
        </p>
        <p>
          <%= f.check_box(:active) %>
        </p>
      </fieldset>
    </div>
    <div class="splitcontentright">
      <fieldset class="box tabular">
        <legend>Emails</legend>
          <p>
            <%= f.select(:created_template_name, @template_files, :required => true) %>
          </p>
          <p>
            <%= f.check_box(:send_created_email_to_user) %>
          </p>
          <p>
            <%= f.select(:closed_template_name, @template_files, :required => true) %>
          </p>
          <p>
            <%= f.check_box(:send_closed_email_to_user) %>
          </p>
          <p>
            <%= f.select(:question_template_name, @template_files, :required => true) %>
          </p>
        </fieldset>
      </div>
      <div class="splitcontentright">
      <fieldset class="box tabular">
        <legend>Exclusions</legend>
          <p>
          <%= f.text_area :domains_to_ignore, :rows => 4, :cols => 29 %>
          <em class="info">
            You can specify a semi-colon separated list of regular expressions that will be checked against the emails from address. If any of the expressios match, the email will be ignored and deleted.
          </em>
        </p>
        <p>
          <%= f.text_area :subject_exclusion_list, :rows => 4, :cols => 29 %>
          <em class="info">
            You can specify a semi-colon separated list of regular expressions to be checked against the email's subject. If the subject matches the email will ignored and deleted.
          </em>
        </p>
        </fieldset>
      </div>
      <div class="splitcontentright">
      <fieldset class="box tabular">
        <legend>Options</legend>
          <p>
            <%= f.check_box(:reply_all_for_outgoing) %>
            <em class="info">
              If this is checked, all email addresses in the incoming email will be added to the reply email address fields, so that all recipients are replied to with ticket creation and any other redmine emails.
            </em>
          </p>
          <p>
            <%= f.text_field :bcc_email %>
            <em class="info">
              You can have all emails that are sent out by Support Helpdesk be blind carbon copied to this email address. Leave blank if you dont want this feature.
            </em>
          </p>
          <p>
            <%= f.check_box :search_in_to %>
            <%=h "To" %>
            <%= f.check_box :search_in_cc %>
            <%=h "Cc" %>
          </p>
        </fieldset>
      </div>
    </div>
    <div style="clear:left;"></div>
      <p>
        <%= f.submit "Save" %>
      </p>
<% end %>

app/views/support_helpdesk_setting/create.html.erb
<h2>SupportHelpdeskSettingController#create</h2>

app/views/support_helpdesk_setting/edit.html.erb
<h2><%= link_to "Support settings", support_helpdesk_settings_path %> >> Edit Support setting</h2>

<%= render 'form' %>

app/views/support_helpdesk_setting/index.html.erb
<div class="contextual">
	<%= link_to "New support setting", new_support_helpdesk_setting_path, :class => "icon icon-add" %>
</div>

<h2>Support Helpdesk settings</h2>
<% if @settings.count > 0 %>
<table class="list">
	<thead>
		<tr>
			<th>Name</th>
			<th>Email address to route</th>
			<th>Email to send as</th>
			<th>Last email process time</th>
			<th>Last email check time</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<%- @settings.each do |s| %>
	<tr>
		<td><%= link_to s.name, edit_support_helpdesk_setting_path(s) %></td>
		<td><%= s.to_email_address %></td>
		<td><%= s.from_email_address %></td>
		<td><%= format_time(s.last_processed) %></td>
		<td><%= format_time(s.last_run) %></td>
		<td class="buttons">
			<%= image_tag((s.active ? 'true.png' : 'exclamation.png'),
                                    :style => "vertical-align:bottom;") %>
			<%= link_to (s.active ? "Deactivate" : "Activate"), activate_support_helpdesk_setting_path(s), :confirm => "Are you sure?", :method => :activate %>
			<%= link_to "Delete", s, :confirm => "Are you sure?", :method => :delete, :class => "icon icon-del" %>
		</td>
	</tr>
	<%- end %>
	</tbody>
</table>
<% else %>
<p class="nodata">No data to display</p>
<div style="clear:both;"></div>
<% end %>

app/views/support_helpdesk_setting/new.html.erb
<h2><%= link_to "Support settings", support_helpdesk_settings_path %> >> New Support setting</h2>

<%= render 'form' %>